[pytest]
filterwarnings =
    error
    ignore:.*httpx.*starlette.testclient.*:starlette.exceptions.StarletteDeprecationWarning
    ignore:The anyio\.abc\.BlockingPortal alias is deprecated.*:DeprecationWarning:starlette.testclient
    ignore:The anyio\.abc\.BlockingPortal alias is deprecated.*:DeprecationWarning:anyio
    ignore:The anyio\.abc\.BlockingPortal alias is deprecated.*:DeprecationWarning
